name: CI

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/**'
      - 'build/**'
      - 'deps/**'
      - 'sources/**'
      - '!**/.all-contributorsrc'
      - '!**/.editorconfig'
      - '!**/.gitignore'
      - '!**/*.md'
  workflow_dispatch:

jobs:
  Linux-Debug:
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit
    with:
      build-type: Debug

  Windows-Debug:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      build-type: Debug

  Windows-Tests:
    uses: ./.github/workflows/test-windows.yml
    secrets: inherit
    with:
      build-type: Release
      test-category: Simple
