name: CI

on:
  push:
    branches:
      - xplat-editor
  pull_request:
    branches:
      - xplat-editor
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  Setup:
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  #
  # Build Stride for Windows
  #
  Windows-Debug:
    needs: Setup
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      build-type: Debug
